//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class AccountEntities : DbContext
{
    public AccountEntities()
        : base("name=AccountEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblUser> tblUsers { get; set; }
    public virtual DbSet<tblLesson> tblLessons { get; set; }
    public virtual DbSet<tblSubject> tblSubjects { get; set; }

    public virtual ObjectResult<GetUsers_Result> GetUsers()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUsers_Result>("GetUsers");
    }

    public virtual ObjectResult<doLogin_Result> doLogin(string email, string password)
    {
        var emailParameter = email != null ?
            new ObjectParameter("email", email) :
            new ObjectParameter("email", typeof(string));

        var passwordParameter = password != null ?
            new ObjectParameter("password", password) :
            new ObjectParameter("password", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<doLogin_Result>("doLogin", emailParameter, passwordParameter);
    }

    public virtual ObjectResult<Getsubject_Result> Getsubject()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getsubject_Result>("Getsubject");
    }

    public virtual ObjectResult<Getlesson_Result> Getlesson()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Getlesson_Result>("Getlesson");
    }

    public virtual ObjectResult<GetLesson2_Result> GetLesson2()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLesson2_Result>("GetLesson2");
    }

    public virtual ObjectResult<GetLesson3_Result> GetLesson3()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLesson3_Result>("GetLesson3");
    }

    public virtual ObjectResult<GetLesson4_Result> GetLesson4()
    {
        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLesson4_Result>("GetLesson4");
    }

    public virtual int DeleteLesson(Nullable<int> lessonID)
    {
        var lessonIDParameter = lessonID.HasValue ?
            new ObjectParameter("lessonID", lessonID) :
            new ObjectParameter("lessonID", typeof(int));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DeleteLesson", lessonIDParameter);
    }
}
