//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblLesson
{
    public int lessonID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public Nullable<int> subjectID { get; set; }

    public virtual tblSubject tblSubject { get; set; }
}

public partial class tblSubject
{
    public tblSubject()
    {
        this.tblLessons = new HashSet<tblLesson>();
    }

    public int subjectID { get; set; }
    public string subjectName { get; set; }

    public virtual ICollection<tblLesson> tblLessons { get; set; }
}

public partial class tblUser
{
    public int userID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Passowrd { get; set; }
}

public partial class doLogin_Result
{
    public int userID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Passowrd { get; set; }
}

public partial class Getlesson_Result
{
    public string Title { get; set; }
    public string Description { get; set; }
    public int lessonID { get; set; }
    public string subjectName { get; set; }
}

public partial class GetLesson2_Result
{
    public int lessonID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string subjectName { get; set; }
}

public partial class GetLesson3_Result
{
    public int lessonID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string subjectName { get; set; }
}

public partial class GetLesson4_Result
{
    public int lessonID { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public string subjectName { get; set; }
}

public partial class Getsubject_Result
{
    public int subjectID { get; set; }
    public string subjectName { get; set; }
}

public partial class GetUsers_Result
{
    public int userID { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Passowrd { get; set; }
}
