//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Accounts
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSubject
    {
        public tblSubject()
        {
            this.tblLessons = new HashSet<tblLesson>();
        }
    
        public int subjectID { get; set; }
        public string subjectName { get; set; }
    
        public virtual ICollection<tblLesson> tblLessons { get; set; }
    }
}
